# Generated by Django 3.2.5 on 2021-08-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_post_publish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
